// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Praticien struct {
	ID          int64
	Name        string
	Firstname   string
	Address     string
	Zip         string
	City        string
	Description sql.NullString
	Profession  string
}
